# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7700ce72cda93f54d81a7ab1fe818f3ece48d7ee8d94fb7de1f8642f1697227928ac4bdbf7081875634b48f0a23a00d718081508d491d39a64760caa5615829

test:
  secret_key_base: caad518fb7c0af6c51b66ddf3b8b8efbb077599baf38482021819bb3deaa0e5023860f80799cf278570aea1d3d978eb9bcbf72f1711cb318fd288d6b4bc14a16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
